version: "3.9"
services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend/generated:/app/generated
      - ./backend/launchspark.db:/app/launchspark.db
      - ./backend/logs:/app/logs
    ports: [ "3001:3001" ]
    restart: unless-stopped
  worker:
    build: ./backend
    command: ["node","worker.js"]
    env_file: ./backend/.env
    volumes:
      - ./backend/generated:/app/generated
      - ./backend/launchspark.db:/app/launchspark.db
      - ./backend/logs:/app/logs
    restart: unless-stopped
  frontend:
    build: ./frontend
  proxy:
    image: nginx:alpine
    ports: [ "8080:80" ]
    volumes: [ "./infra/nginx.conf:/etc/nginx/conf.d/default.conf:ro" ]
    depends_on: [ backend, worker, frontend ]
